version: "3.9"
services:
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  api:
    build: ./customer-app-express
    environment:
      PORT: 3002
      MONGO_URI: mongodb://root:secret@mongo:27017/?authSource=admin
      DB_NAME: Customerdb
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  web:
    build: ./customer-app
    ports:
      - "3000:80"
    depends_on:
      - api

  mongo-express:
    image: mongo-express:1.0.2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
